---
exclude: '^$'
fail_fast: false

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
      args: [-l, "100", --py36]

-   repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
      - id: pylava
        name: pylava
        entry: pylava -o pylava.ini
        language: system
        types: [python]
